services:
  pgdatabase:
    container_name: postgres:13
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    # volumes:
    #   - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    # container_name: pgadmin
    image: dbpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    # volumes:
    #    - "./pgAdmin_data:/var/lib/pgadmin"
    ports:
      - "8080:80"
